apiVersion: v1
kind: Service
metadata:
  name: iris-serving-svc
  namespace: mlops
  labels: 
     app: iris-serving
spec:
  selector:
    app: iris-serving
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: NodePort
